//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LessonsLearned
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> OpenedDate { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<int> ProjectNumber { get; set; }
        public string Resolution { get; set; }
        public string WorkedWell { get; set; }
        public string Project { get; set; }
        public string Client { get; set; }
        public string Location { get; set; }
        public string TRCOffice { get; set; }
        public string DidntWorkWell { get; set; }
        public Nullable<bool> Event { get; set; }
        public Nullable<bool> ProjectReviewLesson { get; set; }
        public Nullable<bool> PandC { get; set; }
        public Nullable<bool> Nuclear { get; set; }
        public Nullable<bool> Substation { get; set; }
        public Nullable<bool> Civil { get; set; }
        public Nullable<bool> Transmission { get; set; }
        public Nullable<bool> Automation { get; set; }
        public Nullable<bool> Distribution { get; set; }
        public Nullable<bool> Construction { get; set; }
        public Nullable<bool> ProjectManagement { get; set; }
        public Nullable<bool> TestingAndCommissioning { get; set; }
        public Nullable<bool> PersonalCommunication { get; set; }
        public Nullable<bool> Drafting { get; set; }
        public Nullable<bool> Procedures { get; set; }
        public Nullable<bool> Training { get; set; }
        public Nullable<bool> Scheduling { get; set; }
        public Nullable<bool> MaterialsOrProcurement { get; set; }
        public Nullable<bool> DesignChangeDevelopment { get; set; }
        public Nullable<bool> VerificationOrCrossCheck { get; set; }
        public byte[] Attachment { get; set; }
        public string AttDesc { get; set; }
        public byte[] Attachment1 { get; set; }
        public string Att1Desc { get; set; }
        public byte[] Attachment2 { get; set; }
        public string Att2Desc { get; set; }
        public byte[] SSMATimeStamp { get; set; }
    }
}
